# fly.toml app configuration file generated for radar-1759647143-autumn-feather-5278 on 2025-10-05T14:52:53+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'radar-1759647143-autumn-feather-5278'
primary_region = 'sin'

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
